server:
  port: 8081
spring:
#  application:
#    name: userservice
  datasource:
    url: jdbc:mysql://localhost:3306/cloud_user?useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.93.132:8848
#        cluster-name: HZ
#        namespace:
#        ephemeral: false
#        service: userservice
        #配置的服务名在 Nacos 中是唯一的,才能设置非临时实例
mybatis:
  type-aliases-package: cn.itcast.user.pojo
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    cn.itcast: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
pattern:
  dateformat: MM-dd HH:mm:ss
#eureka:
#  client:
#    service-url:
#      defaultZone: http://127.0.0.1:10086/eureka