server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cloud_order?useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    sentinel: #微服务保护
      transport:
        dashboard: localhost:8090
      web-context-unify: false # 演示链路时关闭context整合
      datasource:
        flow:
          nacos:
            discovery:
              server-addr: 192.168.93.132:8848
              dataId: orderservice-flow-rules
              groupId: SENTINEL_GROUP
              rule-type: flow # 还可以是：degrade、authority、param-flow
    openfeign:
      client:
        config:
          default:  # default全局的配置
            loggerLevel: BASIC # 日志级别，BASIC就是基本的请求和响应信息
      httpclient:
        enabled: true  #开启feign对HttpClient的支持
        max-connections: 200 # 最大的连接数
        max-connections-per-route: 50 # 每个路径的最大连接数
    nacos:
      discovery:
        server-addr: 192.168.93.132:8848
#        cluster-name: HZ
  #        namespace: 276e038e-021d-4fcf-8477-f902722d8e44
  application:
    name: orderservice
mybatis:
  type-aliases-package: cn.itcast.order.pojo
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    cn.itcast: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
feign:
  sentinel:
    enabled: true # 开启feign对sentinel的支持
# XXJOB参数配置
xxl:
  job:
    accessToken:
    admin:
      addresses: http://192.168.93.132:8093/xxl-job-admin
    executor:
      appname: excutor001
      address:
      ip:
      port: 7878
      logpath: .\logs
      logretentiondays: 30
#eureka:
#  client:
#    service-url:
#      defaultZone: http://127.0.0.1:10086/eureka
